#!/usr/bin/env node
/**
 * Compiles `openapi.yaml` into `backend/src/generated/openapi.ts`, or fails if it is stale.
 *
 * Usage:
 *   node scripts/openapi-types.mjs           regenerate and write
 *   node scripts/openapi-types.mjs --check    compare and exit 1 on a difference
 *
 * ## Why the check is the point, and the generator only the means
 *
 * `npm run openapi:types` had not run since the generated file was first committed. It could
 * not: the backend compiles with `typescript@^7`, the Go port, which publishes `version` and
 * `versionMajorMinor` and none of the compiler API — and `openapi-typescript` builds its output
 * by constructing a TypeScript AST, so it throws on `ts.factory` before it reads a byte of the
 * contract. Nothing invoked it, so nothing reported that.
 *
 * The file then went three contract edits stale, each patched by hand. That is the failure
 * worth preventing, and it is invisible by construction: a stale `paths` type describes a
 * service that no longer exists, and the compiler agrees with it perfectly. So a working
 * generator is not the fix — a build that goes red when the two disagree is. That is `--check`,
 * wired into `npm run verify` and into the CI job that installs this package.
 *
 * ## Why this lives at the root
 *
 * Three homes were possible and two of them are traps.
 *
 * Not `backend/`, which is where it used to be. Two TypeScripts in one `node_modules` collide:
 * both packages declare `bin.tsc`, npm links whichever it linked last, and installing
 * `typescript@5` beside the compiler silently pointed `node_modules/.bin/tsc` — and therefore
 * `npm run typecheck`, the CI step and the Dockerfile — at 5.9.3. Measured, not feared. That is
 * a compiler swap nobody asked for, in a package whose whole point is to be on 7.
 *
 * Not a nested tool package with its own `node_modules` either, though that does isolate the
 * bin. It needs a second install step, and a second install step is one CI can silently not
 * have — which is the same shape of defect as the one being fixed.
 *
 * The root already owns every cross-cutting check (`check:deps`, `check:npmrc`, `check:node`,
 * `check:dependabot`) and it owns `openapi.yaml` itself, because the contract describes the
 * system rather than the backend. It also has no TypeScript of its own and compiles nothing, so
 * there is nothing here for a `typescript@5` to collide with; `backend` and `frontend` each
 * resolve their own 7.x from their own `node_modules` first. No alias, no resolution hook, one
 * lockfile, and Dependabot already watches `/`.
 *
 * ## One code path for both modes
 *
 * Which is why this uses the package's Node API rather than spawning its CLI. A check that
 * generated by a different route from the generator would eventually disagree with it, and then
 * the check would be reporting on something nobody ships. With no flags passed, the CLI is
 * `COMMENT_HEADER + astToString(await openapiTS(schema))` and `COMMENT_HEADER` is the package's
 * own export, so this is byte-identical to it — verified against the committed file, which the
 * first run reproduced exactly.
 *
 * Nothing is written in `--check` mode, so it is safe to run mid-edit and behaves the same on a
 * laptop as in CI — the same property `frontend/scripts/check-i18n.mjs` keeps for the same
 * reason.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString, COMMENT_HEADER } from 'openapi-typescript'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** The contract. Root-level, because it describes the system and not one half of it. */
const CONTRACT = join(root, 'openapi.yaml')
/** What it compiles to. Excluded from Biome (`backend/biome.json`), so never hand-formatted. */
const GENERATED = join(root, 'backend', 'src', 'generated', 'openapi.ts')

/** The command that fixes a stale file, quoted in the failure so nobody has to go looking. */
const FIX = 'npm run openapi:types'

const checking = process.argv.includes('--check')

// A URL rather than the path string: `openapiTS` treats a string as a specifier to resolve and
// a URL as a file to read, and on Windows a drive letter is indistinguishable from a scheme.
const generated = `${COMMENT_HEADER}${astToString(await openapiTS(pathToFileURL(CONTRACT)))}`
const where = relative(root, GENERATED)

if (!checking) {
  writeFileSync(GENERATED, generated)
  console.log(`openapi types: wrote ${where} from openapi.yaml`)
  process.exit(0)
}

let committed
try {
  committed = readFileSync(GENERATED, 'utf8')
} catch {
  console.error(`openapi types: ${where} is missing. Run \`${FIX}\`.`)
  process.exit(1)
}

if (committed === generated) {
  console.log(`openapi types: ok (${where} matches openapi.yaml)`)
  process.exit(0)
}

/**
 * Where the two first differ, and what each says there.
 *
 * A line number and the two lines rather than a full diff: the useful fact is which part of the
 * contract moved, and a diff of a thousand generated lines buries it. The line counts follow
 * because "one line differs" and "four hundred lines were added" want different reactions.
 */
const left = committed.split('\n')
const right = generated.split('\n')
const found = left.findIndex((line, index) => line !== right[index])
// `-1` means one is a prefix of the other, so the first difference is where the shorter ends.
const at = found === -1 ? Math.min(left.length, right.length) : found

console.error(
  `openapi types: ${where} is stale — it no longer matches openapi.yaml.

  first difference at line ${at + 1}:
    committed: ${JSON.stringify(left[at] ?? '<end of file>')}
    contract:  ${JSON.stringify(right[at] ?? '<end of file>')}

  ${left.length} lines committed, ${right.length} generated.

Run \`${FIX}\` and commit the result. Do not edit that file by hand: it is generated, Biome
does not format it, and hand edits are how it went stale in the first place.
`,
)
process.exit(1)
